### ISSUE TITLE
Fails to save if link is behind text

### ISSUE THREAD

**Issue by vronizor** [Rnbsov/Omnivore-Telegram-Bot#8]
Hi again :)

I use the bot to save articles from news outlets, often from other Telegram channels. If the link to the article is plainly written in the text of the forwarded message, it saves fine, but it doesn't recognize the links hidden under some text. The screenshot below shows how the link under "Lien de l'article." is not picked up by the bot.

I was wondering if it was possible to add that functionality? 

Thanks! 

<img width="450" alt="image" src="https://github.com/Rnbsov/Omnivore-Telegram-Bot/assets/22742874/8c3c1c51-30bd-403b-be92-4d5935ea31c0">

**Comment by Rnbsov** [comment]
Hi, thanks for reporting! 📢  
  
From now on bot handle such cases
